theme: jekyll-theme-hacker
# Site
title: Kai's Blog
subtitle: 积极生活，相信未来！
description: 一生只爱一人！
keywords:
author: kai
language: zh-Hans
timezone: Asia/Nanjing
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://lovec.xyz
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
deploy:
  type: git
  repo: https://github.com：tokgofail/loveChen.github.io.git
  branch:master
